-- TBOM Compliance Workstation -- Snowflake Setup Script
-- Run this as ACCOUNTADMIN before using the app

-- Database and schema
CREATE DATABASE IF NOT EXISTS AUDIT_APP_DB;
CREATE SCHEMA IF NOT EXISTS AUDIT_APP_DB.APP_SCHEMA;

USE SCHEMA AUDIT_APP_DB.APP_SCHEMA;

-- Review log: tracks every completed review with dual sign-off
CREATE TABLE IF NOT EXISTS REVIEW_LOG (
    REVIEW_ID NUMBER AUTOINCREMENT,
    REVIEW_TYPE VARCHAR,
    REVIEW_PERIOD VARCHAR,
    STATUS VARCHAR DEFAULT 'IN_PROGRESS',
    REVIEWER VARCHAR,
    REVIEWER_NOTES VARCHAR,
    REVIEWED_AT TIMESTAMP_NTZ,
    APPROVER VARCHAR,
    APPROVER_NOTES VARCHAR,
    APPROVED_AT TIMESTAMP_NTZ,
    EVIDENCE_DATA VARIANT,
    ROW_COUNT NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Review schedule: defines what reviews are needed and when
CREATE TABLE IF NOT EXISTS REVIEW_SCHEDULE (
    REVIEW_TYPE VARCHAR,
    CADENCE VARCHAR,
    OWNER_DESCRIPTION VARCHAR,
    DESCRIPTION VARCHAR,
    NOTIFY_DAYS_BEFORE NUMBER DEFAULT 7,
    ACTIVE BOOLEAN DEFAULT TRUE
);

-- Reviewer/approver assignments
CREATE TABLE IF NOT EXISTS REVIEWERS (
    ID NUMBER AUTOINCREMENT,
    REVIEW_TYPE VARCHAR,
    ROLE VARCHAR,
    SNOWFLAKE_USER VARCHAR,
    EMAIL VARCHAR,
    ADDED_BY VARCHAR,
    ADDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ACTIVE BOOLEAN DEFAULT TRUE
);

-- App configuration
CREATE TABLE IF NOT EXISTS APP_CONFIG (
    CONFIG_KEY VARCHAR PRIMARY KEY,
    CONFIG_VALUE VARCHAR,
    UPDATED_BY VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Settings change log
CREATE TABLE IF NOT EXISTS SETTINGS_CHANGE_LOG (
    ID NUMBER AUTOINCREMENT,
    CHANGE_TYPE VARCHAR,
    DETAILS VARCHAR,
    CHANGED_BY VARCHAR,
    CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed review schedule
MERGE INTO REVIEW_SCHEDULE t
USING (
    SELECT * FROM VALUES
        ('failed_login', 'MONTHLY', 'Product Admin(s) - DG and CS', 'Review failed login attempts for suspicious activity', 7, TRUE),
        ('change_log', 'MONTHLY', 'Product Admin(s) - DG and CS', 'Review DDL/security changes - medium and high severity items', 7, TRUE),
        ('pci_data', 'QUARTERLY', 'Info Sec', 'Verify PCI data has proper classification and masking', 14, TRUE),
        ('user_access', 'SEMI_ANNUAL', 'Product Admin(s) - DG and CS', 'Review users, disable 90-day inactive, compare to HR', 14, TRUE),
        ('role_access', 'ANNUAL', 'Product Admin(s) - DG and CS', 'Review roles and assigned privileges', 30, TRUE),
        ('audit_confirm', 'ANNUAL', 'Info Sec', 'Confirm all scheduled reviews were completed', 30, TRUE)
    AS s(REVIEW_TYPE, CADENCE, OWNER_DESCRIPTION, DESCRIPTION, NOTIFY_DAYS_BEFORE, ACTIVE)
) s ON t.REVIEW_TYPE = s.REVIEW_TYPE
WHEN NOT MATCHED THEN INSERT VALUES (s.REVIEW_TYPE, s.CADENCE, s.OWNER_DESCRIPTION, s.DESCRIPTION, s.NOTIFY_DAYS_BEFORE, s.ACTIVE);

-- Set main account config
MERGE INTO APP_CONFIG t
USING (
    SELECT 'IS_MAIN_ACCOUNT' AS CONFIG_KEY, 'TRUE' AS CONFIG_VALUE, CURRENT_USER() AS UPDATED_BY
) s ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT VALUES (s.CONFIG_KEY, s.CONFIG_VALUE, s.UPDATED_BY, CURRENT_TIMESTAMP());

-- Grant usage for the app
GRANT USAGE ON DATABASE AUDIT_APP_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA AUDIT_APP_DB.APP_SCHEMA TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AUDIT_APP_DB.APP_SCHEMA TO ROLE ACCOUNTADMIN;
